### ISSUE TITLE
How to generate gt_2d_semantics, gt_2d_panoptics, lidar_depth?

### ISSUE THREAD

**Issue by Asparagus15** [fuxiao0719/PanopticNeRF#1]
Many thanks for this great work!

When evaluating, there are three files needed, `gt_2d_semantics, gt_2d_panoptics` and `lidar_depth`. 

How could I prepare these files from the original Kitti360 data? Could there be a code release to generate these files?

**Comment by fuxiao0719** [comment]
Currently, 'gt_2d_semantics' and 'gt_2d_panoptics' are manually annotated, thus the GTs are very sparse; 'lidar_depth' is measured by LiDAR equipments.
