### ISSUE TITLE
Lidar depth data conversion

### ISSUE THREAD

**Issue by chih-hao-lin** [fuxiao0719/PanopticNeRF#10]
Thank you for this great work!

In the provided dataset, there are lidar depth files: lidar_depth/[seq_id]/*.npy
Are these files converted from the raw SICK scans in the original Kitti360 dataset?
If so, how can I convert them (from Kitti360 to the provided format)? Would you like to share sample code?
Thank you!

**Comment by fuxiao0719** [comment]
Hi, zhihao, thx for your interest in our project. To obtain our lidar depth gt, we perform multi-frame fusion, which involves fusing multiple frames into a point cloud and reconstructing it by mesh. Based on this mesh, we determine the occlusion relationship and retain only the points that are not occluded in the current frame. We then project these points on 2D map (Supp. 2.2). As for the sample code, these lidar points were generated by Yiyi Liao when she did her postdoc at MPI several years ago, so it may be hard to retrieve the codes now, sorry for that. However, Yiyi did it following the similar pipeline of "Sparsity invariant cnns", maybe you can find more information in that paper.

**Comment by chih-hao-lin** [comment]
Thanks for your reply!
