### ISSUE TITLE
How to generate the visible_id file?

### ISSUE THREAD

**Issue by DevXiaoYan** [fuxiao0719/PanopticNeRF#11]
Thanks for your excellent work!!!

When I was processing data, I encountered the visible_id file, but the kitti-360 official website does not have this file. How should I generate it, please?

Best wishes

**Comment by fuxiao0719** [comment]
Hi, thx for your interest in our work! We generate the visible_id file using our labeling tool. Since it serves as intermediate products, we didn't provide it in the official website. Do you want visible_id in the other sequences?

**Comment by DevXiaoYan** [comment]
Hi,
thank you for the quick reply.&nbsp;I want to reproduce it on my own dataset. Can you describe the meaning of visible_id?







                       
Original
                       
                     

From:"Xiao Fu"< ***@***.*** &gt;;

Date:2023/6/26 20:23

To:"fuxiao0719/PanopticNeRF"< ***@***.*** &gt;;

CC:"Dreamer168"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [fuxiao0719/PanopticNeRF] How to generate the visible_id file?(Issue #11)




 
Hi, thx for your interest in our work! We generate the visible_id file using our labeling tool. Since it serves as intermediate products, we didn't provide it in the official website. Do you want visible_id in the other sequences?

**Comment by fuxiao0719** [comment]
Hi, 'visible_id' denotes per-frame visible bounding primitive IDs. More specifically, we annotate the bbox via lidar points, and the 'visible_id' files are generated via projecting the accumulated 3D points to the image plane, where a reconstructed mesh is used to filter out occluded points. The ids of the non-occluded points are saved in the 'visible_id' file.

**Comment by DevXiaoYan** [comment]
Thank you for your reply. 
May I ask again, if I only have multi-view images and corresponding depth sgm and split pseudo-label files, will the performance be greatly affected? Or the performance impact of not using bounding primitive?

                       
Original
                       
                     

From:"Xiao Fu"< ***@***.*** &gt;;

Date:2023/6/27 10:41

To:"fuxiao0719/PanopticNeRF"< ***@***.*** &gt;;

CC:"Dreamer168"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [fuxiao0719/PanopticNeRF] How to generate the visible_id file?(Issue #11)




 
Hi, 'visible_id' denotes per-frame visible bounding primitive IDs. More specifically, we annotate the bbox via lidar points, and the 'visible_id' files are generated via projecting the accumulated 3D points to the image plane, where a reconstructed mesh is used to filter out occluded points. The ids of the non-occluded points are saved in the 'visible_id' file.

**Comment by fuxiao0719** [comment]
Well, I think that the performance will correspondingly drop a bit as bounding primitives provide deterministic sampling regions and indirect geometry help (see "fixed semantic field" in our paper). In your situation, I recommend using official Semantic NeRF & PNFs.

**Comment by DevXiaoYan** [comment]
Do you think it is feasible to use an RGB-only 3d object detection network and tracker to predict and output 3D bounding box of objects in clip for a period of time as bounding primitives?


                       
Original
                       
                     

From:"Xiao Fu"< ***@***.*** &gt;;

Date:2023/6/27 12:00

To:"fuxiao0719/PanopticNeRF"< ***@***.*** &gt;;

CC:"Dreamer168"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [fuxiao0719/PanopticNeRF] How to generate the visible_id file?(Issue #11)




 
Well, I think that the performance will correspondingly drop a bit as bounding primitives provide deterministic sampling regions and indirect geometry help (see "fixed semantic field" in our paper). In your situation, I recommend using official Semantic NeRF &amp; PNFs.

**Comment by fuxiao0719** [comment]
I think it feasible to achieve so via two potential approachs. 1. Like PNFs (CVPR'22), use off-the-shelf predictors. 2. Like NeRF-RPN (CVPR'23), integrate 3D RPN predictors into 3D underlying scene features. But I am not sure of their accuracies.

**Comment by DevXiaoYan** [comment]
Thank you for your advice. I want to generate automatic annotation in the automatic driving scene, so I have read a lot of articles to locate your article and feel very good. Hope to have the opportunity to exchange learning!


                       
Original
                       
                     

From:"Xiao Fu"< ***@***.*** &gt;;

Date:2023/6/27 13:41

To:"fuxiao0719/PanopticNeRF"< ***@***.*** &gt;;

CC:"Dreamer168"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [fuxiao0719/PanopticNeRF] How to generate the visible_id file?(Issue #11)




 
I think it feasible to achieve so via two potential approachs. 1. Like PNFs (CVPR'22), use off-the-shelf predictors. 2. Like NeRF-RPN (CVPR'23), integrate 3D RPN predictors into 3D underlying scene features. But I am not sure of their accuracies.

**Comment by fuxiao0719** [comment]
Sure :)
