### ISSUE TITLE
About sky depth without using NDC space

### ISSUE THREAD

**Issue by DRosemei** [fuxiao0719/PanopticNeRF#3]
Thanks for your great work! I found that you used real world space coordinate instead of common NDC space. So I want to know how you supervise sky depth cause it is inf depth in real world. I found that you filted it out when training [here](https://github.com/fuxiao0719/PanopticNeRF/blob/b50c38687be2f4745f78f253d217f297a545c3e0/lib/train/losses/panopticnerf.py#L71)

**Comment by fuxiao0719** [comment]
Thanks for reaching out. Actually we only supervise the foreground depth via weak depth supervision, because the SGM algorithm fails to produce accurate boundaries and depth in the far region.

**Comment by DRosemei** [comment]
@fuxiao0719 Thanks for your reply. So you only supervise depth except sky. When you visualize, you just give sky a far depth.  Is that right?
![image](https://user-images.githubusercontent.com/27892562/177683358-d8887e2e-6a4e-4c84-8c1f-88562931f357.png)

**Comment by fuxiao0719** [comment]
Yes. As you can see in "Sampling Strategy and Sky Modeling", if a camera ray intersects less than 10 bounding primitives, we additionally sample a set of points to model the sky in [t_max, t_max + t_int], where t_max denotes the distance from the origin to the furthest bounding primitive and t_int is a constant distance interval.
