### ISSUE TITLE
Intersections over road surface

### ISSUE THREAD

**Issue by DRosemei** [fuxiao0719/PanopticNeRF#4]
I find [this ](https://github.com/fuxiao0719/PanopticNeRF/blob/b50c38687be2f4745f78f253d217f297a545c3e0/lib/networks/panopticnerf.py#L25)will largely enforce NeRF to converge to proper depth. While intersections are from 3D bboxes, so how do you deal with road surface? I cannot see from [here](https://github.com/fuxiao0719/PanopticNeRF/blob/b50c38687be2f4745f78f253d217f297a545c3e0/figs/ray_mesh_intersection.png). Thanks in advance : )

**Comment by DRosemei** [comment]
I find that you said 3D primitives cover the full scene, so dose they include road surface?
![image](https://user-images.githubusercontent.com/27892562/178737217-9477e00a-ef86-4738-9a57-e024ecd601c5.png)

**Comment by fuxiao0719** [comment]
Road surface is enclosed by the thin 3D primitives as well.
