### ISSUE TITLE
How to generate 'visible_id' files?

### ISSUE THREAD

**Issue by Asparagus15** [fuxiao0719/PanopticNeRF#5]
As titled.

**Comment by yiyiliao** [comment]
Hi, the 'visible_id' files are generated via projecting the accumulated 3D points to the image plane, where a reconstructed mesh is used to filter out occluded points. The ids of the non-occluded points are saved in the 'visible_id' file. Are you interested in generating the 'visible_id' files for other frames of the KITTI-360 dataset or for another dataset?
