### ISSUE TITLE
Hi，could “PanoticNeRF” handle dymatic object?

### ISSUE THREAD

**Issue by yushengjiexy** [fuxiao0719/PanopticNeRF#6]
能处理动态汽车吗

**Comment by fuxiao0719** [comment]
Currently not available, but our method can be extended to dynamic scenes leveraging recent advances in dynamic radiance field estimation, e.g. Neural scene graphs for dynamic scenes.

**Comment by yushengjiexy** [comment]
学弟，对谷歌的全景nerf有了解吗，它的动态物处理有相关开源推荐吗

**Comment by fuxiao0719** [comment]
Yes, I think their work may be based on the neural scene graph (https://github.com/princeton-computational-imaging/neural-scene-graphs) I mentioned above.

**Comment by yushengjiexy** [comment]
thanks
