### ISSUE TITLE
xyz /= cfg.dist

### ISSUE THREAD

**Issue by tangtaogo** [fuxiao0719/PanopticNeRF#9]
Thanks for your great work! 
I was confused by the code on [this line](https://github.com/fuxiao0719/PanopticNeRF/blob/3d3ef46e721de8935854fc62847f657f34be893f/lib/networks/panopticnerf.py#L39)
The xyz is in real world space coordinate. The cft.dist denotes the distance from the origin to the furthest bounding primitive.

**Comment by fuxiao0719** [comment]
Thank you for your interest. Generally speaking, a normalized coordinate system (such as ndc system) is more suitable for Position Encoding, thus we normalize the world coordinate system by the underlined code. The reason that we don't use ndc system is that it will fail in the common case of large-range view changes, such as turning, in the driving scenario.

**Comment by tangtaogo** [comment]
Thanks for your kind reply!
Moreover, I found the transformation  [pose[:3, 3] = pose[:3, 3] - self.translation](https://github.com/fuxiao0719/PanopticNeRF/blob/3d3ef46e721de8935854fc62847f657f34be893f/lib/datasets/kitti360/panopticnerf.py#L158).  

In my understanding, the cft.center_pose is the camera pose of the center frame of the sequence and the cft.dist is from subtracting the nearest frame from the farthest frame of the sequence.  So that the xyz can be normalized by cft.dist to [-1,1].
But the cft.dist is just one value, how to normalize the three-dimensional xyz from real world space coordinate?

**Comment by fuxiao0719** [comment]
Well, the normalization here is not strictly normalized to the [-1,1] (ndc system), it's an approximation to [-pi/2, pi/2]. As monotonic interval of sinusoid function is pi, we need to normalize the signals, which will be passed to the position encoding, to a monotonic range so that every signal has unique embedding in the embedding space. In our experiment, we find that cft.dist is a simple but good choice, and of course, you can try other normalization approaches that may result in better outcomes.

**Comment by tangtaogo** [comment]
Thank you for your patient explanation!
Can you share some experience on how to choose the appropriate dist? As the dist differs for different sequence on the configs(210/250/270).

**Comment by fuxiao0719** [comment]
Hi, in a scene we simply take the farthest distance + constant [20,100] as cfg.dist. The constant scales with the farthest distance. You can estimate the farthest distance from [here](https://github.com/fuxiao0719/PanopticNeRF/blob/3d3ef46e721de8935854fc62847f657f34be893f/recenter_pose.py#L235-L236).

**Comment by tangtaogo** [comment]
Thanks a lot!
